### ISSUE TITLE
Replacement codes broken

### ISSUE THREAD

**Issue by mikkonid** [NordicID/ar8x_app_hidreader#3]
Couple of issues in commit
https://github.com/NordicID/ar8x_app_hidreader/commit/a4dab22231734a46ec39f8f7529a943c99afe4d7

See comments
https://github.com/NordicID/ar8x_app_hidreader/commit/a4dab22231734a46ec39f8f7529a943c99afe4d7#r60281012
https://github.com/NordicID/ar8x_app_hidreader/commit/a4dab22231734a46ec39f8f7529a943c99afe4d7#r60281087
https://github.com/NordicID/ar8x_app_hidreader/commit/a4dab22231734a46ec39f8f7529a943c99afe4d7#r60281064

**Comment by ekkilm** [comment]
https://github.com/NordicID/ar8x_app_hidreader/commit/0e83bd326a2e58ca663a8ada32fc9db783f6aa26
Replacement code fixed
