### ISSUE TITLE
UI interface not loading without internet access

### ISSUE THREAD

**Issue by alexit84** [NordicID/ar8x_app_hidreader#5]
Hello,
I have an installation without public internet access and this HID Reader apps, working great. 
Unfortunately the UI interface is unable to load because is requiring some asset (CSS, JS, libs) available online trough public addresses or CDN.

Is it possibile to remove dependancy from public URIs ?

Thanks!

**Comment by ekkilm** [comment]
Hi Alex and sorry for very late reply. Finally I fixed this issue.

See my commit
https://github.com/NordicID/ar8x_app_hidreader/commit/23ea60678b254fe20ef958eefb5c68381c4bc95b
